// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-about.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_about_default = defineTool({
  name: "get_about",
  title: "Get about",
  description: "Get Nikhil Raj's bio, background, and frontend web development journey.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Nikhil Raj \u2014 Frontend Web Developer.",
          "",
          "Education: B.Tech in Metallurgical and Materials Science Engineering at MANIT Bhopal (2025-2029), currently in the 3rd semester with a CGPA of 6.8.",
          "",
          "Background: Studied at Jawahar Navodaya Vidyalaya (JNV) and represented JNV in wrestling, which built discipline and consistency.",
          "",
          "Skills: HTML, CSS, JavaScript, Python, C, Git & GitHub, Netlify deployment, responsive and mobile-first design, AI-assisted development tools.",
          "",
          "Current focus: Building responsive websites, landing pages, and modern web applications, and learning advanced JavaScript and React.js."
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/tools/get-education.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_education_default = defineTool2({
  name: "get_education",
  title: "Get education",
  description: "Get Nikhil Raj's education history and academic achievements.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Education:",
          "- Jawahar Navodaya Vidyalaya (JNV) \u2014 schooling",
          "- Class 12: Represented at national level in wrestling",
          "- Completed HTML, CSS, JavaScript, and Git & GitHub self-learning tracks",
          "",
          "Next goal: Become a digital advertising expert (Google Ads, Facebook Ads, PPC)."
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/tools/get-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_projects_default = defineTool3({
  name: "get_projects",
  title: "Get projects",
  description: "List Nikhil Raj's public projects and GitHub repositories.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const projects = [
      {
        name: "Contact Form",
        description: "HTML/CSS/JS contact form built while learning web basics.",
        repo: "https://github.com/nikhilgamingff8-cyber/contact-form"
      },
      {
        name: "HTML Day 1",
        description: "First HTML/CSS/JS practice project.",
        repo: "https://github.com/nikhilgamingff8-cyber/HTML-day-1"
      },
      {
        name: "Portfolio",
        description: "This portfolio site.",
        repo: "https://github.com/nikhilgamingff8-cyber"
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
      structuredContent: { projects }
    };
  }
});

// src/lib/mcp/tools/get-skills.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_skills_default = defineTool4({
  name: "get_skills",
  title: "Get skills",
  description: "List Nikhil Raj's technical skills across programming, web development, and tools.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const skills = {
      programming: ["HTML5", "CSS3", "JavaScript", "Python", "C"],
      web_development: [
        "Responsive Web Design",
        "Landing Page Development",
        "Website Deployment",
        "Mobile First Design"
      ],
      tools: [
        "VS Code",
        "Git",
        "GitHub",
        "Netlify",
        "Google AI Studio",
        "Canva",
        "Google Sheets"
      ],
      currently_learning: ["Advanced JavaScript", "React.js", "AI Assisted Development"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
      structuredContent: skills
    };
  }
});

// src/lib/mcp/tools/send-contact-message.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var send_contact_message_default = defineTool5({
  name: "send_contact_message",
  title: "Send contact message",
  description: "Send a message to Nikhil Raj via the portfolio contact form.",
  inputSchema: {
    name: z.string().trim().min(1).describe("Sender's full name"),
    email: z.string().trim().email().describe("Sender's email address"),
    subject: z.string().trim().min(1).describe("Message subject"),
    message: z.string().trim().min(1).describe("Message body")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ name, email, subject, message }) => {
    const env = globalThis.process?.env ?? {};
    const url = env.SUPABASE_URL;
    const anon = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY;
    if (!url || !anon) {
      return {
        content: [{ type: "text", text: "Contact service is not configured." }],
        isError: true
      };
    }
    try {
      const res = await fetch(`${url}/functions/v1/send-contact-email`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${anon}`,
          apikey: anon
        },
        body: JSON.stringify({ name, email, subject, message })
      });
      const text = await res.text();
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `Failed to send message: ${text}` }],
          isError: true
        };
      }
      return {
        content: [{ type: "text", text: "Message sent successfully. Nikhil will get back to you soon." }]
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Error sending message: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "nikhil-raj-portfolio-mcp",
  title: "Nikhil Raj Portfolio",
  version: "0.1.0",
  instructions: "Tools for Nikhil Raj's portfolio. Read the about, education, projects, and skills, or send a contact message via `send_contact_message`.",
  tools: [get_about_default, get_education_default, get_projects_default, get_skills_default, send_contact_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
